### ISSUE TITLE
Orderbook details

### ISSUE THREAD

**Issue by pablofullana** [0xProject/0x-launch-kit-frontend#28]
- [x] Parent of #42 (Orderbook is not subtracting filled values)
- [x] Parent of #59 (Add 'My Size' column to Orderbook)
- [ ] Parent of #60 (Pad sizes with 0)

*More items to be added*
